name: BFFLESS Download Artifact
# You may pin to the exact commit or the version.
# uses: bffless/download-artifact@a9310cca5b3391a1ab718d9f04466ffa62c2dae3
uses: bffless/download-artifact@v1.1.0
with:
  # Base URL of the BFFLESS hosting platform
  api-url: ${{ vars.BFFLESS_URL }}
  # API key for authentication (X-API-Key header)
  api-key: ${{ secrets.BFFLESS_API_KEY }}
  # Branch to download from (gets latest deployment)
  branch: main
