name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare static files
        run: |
          mkdir -p dist
          
          cp index.html script.js style.css dist/ || true
          cp -r assets pieces posts dist/ || true

      # Upload the build
      - uses: bffless/upload-artifact@v1.1.1
        with:
          path: dist
          api-url: ${{ vars.BFFLESS_URL }}
          api-key: ${{ secrets.BFFLESS_API_KEY }}
          branch: main
